baseurl = "http://www.it.uu.se/education/course/homepage/introdat/ht16/"
languageCode = "sv-se"
title = "Introduktion till datorer"
theme="introit16"

# Build settings
builddrafts = false
canonifyurls = true
disablerss = true

# Parameters
[Params]
quote = "Uppsala universitet 2016"
email = "intro@it.uu.se"
banner = "images/banner.jpg"
logo = "images/logo.jpg"
